### ISSUE TITLE
Getting cors issue

### ISSUE THREAD

**Issue by kl-narayana-soulpage** [brynlewis/C-CDA_Viewer#10]
While running index file in local after upload xml file then i click on view getting cors issue

**Comment by bd** [comment]
same:
```
Access to XMLHttpRequest at 'file:///Users/me/Downloads/C-CDA_Viewer-master/cda.xsl' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
```

was able to work around CORS with 

```bash
cd ~/Downloads/me/CDA_Viewer-master
python -m http.server 8888
```
then visiting http://localhost:8888/index.htm

This requires having python3 installed.

**Comment by brynlewis** [comment]
The Viewer uses xslt in the browser, which enables the fileset to be a standalone solution.

As mentioned in documentation, xslt in the browser requires that the browser allows a local file to be loaded (using file:). 

Potential solutions for this:
-use a browser that allows this by default (I'm not going to track this)
-change browser preferences
-install a local http server (eg python)

Anything else requires installation of an executable - see the application version of the Viewer - [https://backbeachsoftware.com.au/?cmd=getsql&sid=&id_topic=59&id_site=1](url)
