### ISSUE TITLE
Missing js/purejs.js

### ISSUE THREAD

**Issue by devdaniel** [brynlewis/C-CDA_Viewer#11]
Referenced in index.html but missing js/purejs.js, application can not load non-sample documents.

**Comment by brynlewis** [comment]
index.html does not exist in the src.
index.htm does exist but it doesn't reference purejs.js

You may be talking about the CDA viewer application, but that is not on github.

Non-sample CCDA documents can be opened. If _your_ document can't be opened, support is available.
