### ISSUE TITLE
pure.js missing

### ISSUE THREAD

**Issue by grosch** [brynlewis/C-CDA_Viewer#3]
The bottom of index.html references js/purejs.js which is not part of the distribution

**Comment by jssuttles** [comment]
It doesn't seem like it's used.

**Comment by dod-shamshad** [comment]
Pure.js is missing. Viewer is not able to load files, can't take input and show result. 
<img width="1704" alt="Screen Shot 2021-03-12 at 10 59 16 AM" src="https://user-images.githubusercontent.com/79548042/110986146-26eb1780-8322-11eb-9c12-89914add00db.png">

**Comment by ddmer547** [comment]
> Pure.js丢失。Viewer无法加载文件，无法接受输入并显示结果。
> <img alt="屏幕截图2021-03-12 at 10 59 16 AM" width="1704" src="https://user-images.githubusercontent.com/79548042/110986146-26eb1780-8322-11eb-9c12-89914add00db.png">

你找到了吗？

**Comment by ddmer547** [comment]
> > Pure.js丢失。Viewer无法加载文件，无法接受输入并显示结果。
> > <img alt="屏幕截图2021-03-12 at 10 59 16 AM" width="1704" src="https://user-images.githubusercontent.com/79548042/110986146-26eb1780-8322-11eb-9c12-89914add00db.png">
> 
> 你找到了吗？

或许你可以使用火狐浏览器跨域访问试试

**Comment by John-Nagle** [comment]
Yes, still failing.

**Comment by brynlewis** [comment]
A local file installation will not work in chrome, because chrome will not load local javascript files.  The chrome error message is trying to tell you this.

It will work in firefox locally.

To run it in chrome you need to run it via a http server (local or otherwise).
