### ISSUE TITLE
Unable to view C-CDA

### ISSUE THREAD

**Issue by quagly** [brynlewis/C-CDA_Viewer#4]
Running locally from a git clone using Safari 11.0.1 on OSX 10.12.6.  

* When I copy/paste my own C-CDA or one from the samples directory and click 'View' nothing happens
* When I click 'Show XML'  for sample anything I have pasted is removed, but no new XML appears

I have javascript enabled.  I used the demonstration version and it worked fine.  I need to run locally.  I am on OSX and I understand that the desktop version is Windows only.  

How can I access local C-CDA docs?

**Comment by quagly** [comment]
Update:  I tried using nginx instead of pointing my browser at local files.  Now the xml loads when I click on Show XML, but the view button still does not respond.  I also tried chrome which I understand should work with nginx with the same results.

**Comment by quagly** [comment]
I got this to work using Firefox 52.0.2 instead of Chrome or Safari.  Please support current Chrome and Safari.

**Comment by brynlewis** [comment]
Chrome (and Safari) are supported, however the default setting for Chrome and Safari won't allow a transform using a local xsl file. You can adjust your security settings to allow them to do it, but they won't do it by default.

This isn't something I can control via Javascript, it is part of the browser settings.

-This is mentioned in the readme (though it may not be clear).

If you are running a web server on your local machine, you can serve the fileset from there, allowing you to use Chrome and Safari.

The desktop version is Windows only, yes. If you have a Windows machine on your network, you can run it from there (as a service), and then access it on port 7750 from any other machine on your network.

**Comment by quagly** [comment]
Disabling local file restrictions on safari worked.  Funny that serving the files from nginx didn't.  Thanks for the advice.  Interesting to try the windows from a port.  Do you just point the browser at that port?

**Comment by brynlewis** [comment]
If the CDA Viewer application is running on your network (as an application or a service), you can point your browser here to view a rendered CDA document:
http://<server_ip>:7750/?cda=<cda_filename>

It requires the full path to the filename. Also, your server will need to be able to access the file at that location.

Full info on Viewer integration is here:
http://backbeachsoftware.com.au/?cmd=getsql&id_site=1&id_topic=66
